### ISSUE TITLE
Development haitus

### ISSUE THREAD

**Issue by wrongu** [Rochester-NRT/RocAlphaGo#114]
A GitHub Issue seemed like a reasonable way to post this message:

As the de-facto primary developer on this project, I unfortunately will not be contributing to it until I am certain that no copyright or ownership issues will arise. With any luck, this will be sorted out quickly and development will resume.

Others are, of course, encouraged to continue contributing via pull requests!

**Comment by jtauber** [comment]
What is the concern about copyright and ownership?

**Comment by wrongu** [comment]
Not for the project, just for myself. I'm working at Google for the summer. And after reading the fine print of the employment agreement, I decided to do the safe thing and not contribute until I get an official ok.

**Comment by jtauber** [comment]
Yep, understood. Makes perfect sense and wise decision.

**Comment by blackchaec** [comment]
Understood :)

2016년 6월 6일 (월) 오후 3:09, James Tauber <notifications@github.com>님이 작성:

**Comment by wrongu** [comment]
Update: the "official ok" is looking very unlikely. I may be out for the whole summer.

**Comment by robert-waite** [comment]
Very impressed with the project. Toiled with the paper and finding this repo really filled in the blanks. Bet you a dollar if you sent an email to ole David Silver or the wise Hassabis.. and were like bro.. cmon.. alphago for the masses.. the hello world of DCNN... they would pull some strings ;)
