### ISSUE TITLE
when i run the AlphaGo.training.supervised_policy_trainer  find a ValueError

### ISSUE THREAD

**Issue by lihui2090** [Rochester-NRT/RocAlphaGo#116]
I don`t know why?
Who can help me !
**python -m AlphaGo.training.supervised_policy_trainer my_model.json debug_feature_planes.hdf5 training_results/ --epochs 5 --minibatch 64 --learning-rate 0.01**  

`Using Theano backend.
Epoch 1/5
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/alphgo/RocAlphaGo/AlphaGo/training/supervised_policy_trainer.py", line 221, in <module>
    run_training()
  File "/opt/alphgo/RocAlphaGo/AlphaGo/training/supervised_policy_trainer.py", line 218, in run_training
    nb_val_samples=n_val_data)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 632, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1337, in fit_generator
    raise e
**ValueError: CorrMM images and kernel must have the same stack size**

Apply node that caused the error: CorrMM{half, (1, 1)}(convolution2d_input_1, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 106
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(64, 46, 19, 19), (128, 12, 5, 5)]
Inputs strides: [(66424, 1444, 76, 4), (1200, 100, -20, -4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{add,no_inplace}(CorrMM{half, (1, 1)}.0, Reshape{4}.0), Elemwise{Composite{(i0 * (Abs(i1) + i2 + i3))}}[(0, 2)](TensorConstant{(1, 1, 1, 1) of 0.5}, Elemwise{add,no_inplace}.0, CorrMM{half, (1, 1)}.0, Reshape{4}.0)]]`

**Comment by wrongu** [comment]
There should definitely be more helpful error messages for this kind of thing. It looks like you might have a mismatch between the input size expected by `my_model.json` and the size of the data in `debug_feature_planes.hdf5`. When you run `AlphaGo.preprocessing.game_converter`, the `--features` argument there must match the list of features passed to your model's constructor..

Changing this interface to be more intuitive and/or print more useful debugging messages would be a welcome contribution!

**Comment by AdrianYe** [comment]
You must have used the first debug_feature_planes.hdf5 file in the manual to run the command. 
I got this error too, when I switch to the one created with find lee_*, it works

**Comment by robert-waite** [comment]
Guessing the params you passed to generate the my_model.json file didnt match what you passed to gen data. The model json file doesnt come with project.. there is a slight mismatch that the sgf dataset allows --all but the code in wiki does not allow all.
