### ISSUE TITLE
Mapping RocAlphaGo to Stock Trading ? any idea 

### ISSUE THREAD

**Issue by developeralgo8888** [Rochester-NRT/RocAlphaGo#117]
Is there someone who has an idea of how to map ROCAlphaGo / AlphaGo / GO board rules to Stock trading or Forex trading . I am not sure how to map the board game so as to imitate or simulate a stock market trading 

e.g Black = Sell order or seller  and White = Buy order or Buyer and so on

**Comment by apetresc** [comment]
... I guarantee you this attempt will not be fruitful. Look at a more general-purpose machine-learning library, not a set of models specifically trained for a single board game.

**Comment by wrongu** [comment]
Closing this because it is not an issue with RocAlphaGo. And I agree with apetresc - AlphaGo is a fairly special-purpose program for playing Go. Any connection to something like stock trading would be by analogy only
