### ISSUE TITLE
Possible model checkpointing error with Keras 1.0.0

### ISSUE THREAD

**Issue by robert-waite** [Rochester-NRT/RocAlphaGo#118]
I was playing with the project and the pipeline. I used the game converter to get an hdf5 file from about 10000 sgfs. I then used the SL trainer code to train on the dataset. After the first epoch... i could see the weights file created. I wanted to see how the network would do against GnuGo and tried to load up the model with the code described in the wiki for running gtp.

When it tries to load the output of the SL stage... it throws an error like this:

"Exception: You are trying to load a weight file containing 17 layers into a model with 16 layers."

I believe this was resolved in Keras... after version 1.0.0. Perhaps the requirements.txt files should be updated? Has anyone else had this issue? I tried running gtp with the model and weights file provided in the data repository... and it loaded just fine. Wondering if the way I ran caused this... or if people who are running it actually have a higher version of Keras

https://github.com/fchollet/keras/issues/2281

I upgraded to Keras 1.0.5... but was a 3 hour run to get the file... so didnt have time to check. Will try again tonight to see if it resolved it for me.

**Comment by wrongu** [comment]
I remember seeing this bug a while back, and I think I was able to fix it locally by regenerating my model.json files after upgrading keras

**Comment by robert-waite** [comment]
Wow... such fast response ;)

I tried regenerating the model.json files and had the same issue. I think once the model is written to file... it is busted unless you manually remove the input layer that was incorrectly placed in there. I will try tonight to see if the generation stage works with the updated version of Keras.

Also possible that other people don't see the issue because they are using a different combination or params... but i think mine were fairly straight-forward... can give command lines I used later today if it isn't resolved with the upgrade of keras.

Amazing project btw... spent 1 week reading the AlphaGo paper and referenced papers... just when I figured I would try to tackle the SL on my own... I found your project... really clean too ;) Thanks!

**Comment by robert-waite** [comment]
Creating the checkpoint hdf5 file with version 1.0.5 of keras was loadable by the api. I think updating the requirements file should resolve.. but dont know about stability of keras related to this project.

Trained SL on defaults like the paper.. minus ladder feature planes and 128 filters instead of 192 on a KGS 2006 dataset of around 10k non-pro high-level amateur games which translated to around 2 million state,action pairs before translation. Trained on a modest 660gtx... took around 4 hrs to complete 1st epoch and ran 10 matches through gomill using the 1st epoch SL net vs. GnuGo at lvl 10  and the SL lost every match.

However, looked through some matches and it does know how to play and did win... if... it knew when to pass. Was really surprised watching the games and seeing it knew how to play after simply watching 10k games over 4 hrs. And it won a lot if it used sensible passing.. but the network was trained to pick a move.. and doesnt know about passing. Just gotta move!

I think this is where the second pillar of awesome comes in which is MCTS however basic. Playing this thing to beat current levels of crazystone or zen seems fully possible using just an SL if it could do just a little bit of look ahead. I am interested to see the results of even the most naive rollout policies combined with the SL network in the tree search.

**Comment by wrongu** [comment]
Cool. There has been some discussion on the Gitter channel (which would be a better place to discuss these things - there's a link in the readme) about how having the 8-move history features enables it to memorize certain patterns and jump starts the training (if you remove the `turns_since` feature, you should see much worse gameplay after only 1 epoch).

If the model checkpoint error was fixed, please make a PR with the necessary changes and close this issue

**Comment by robert-waite** [comment]
Addressed by PR
