### ISSUE TITLE
gtp library has bug with pass move

### ISSUE THREAD

**Issue by robert-waite** [Rochester-NRT/RocAlphaGo#119]
I suppose I should report it over in that repo... but because the version needs to be updated here to function figured I should throw it in here too.

I was trying to test a trained SL network against GnuGo using gomill. When GnuGo passes... the gtp library has an error in a function called vertex_in_range() which does a check that the x and y of a vertex are greater than one. A pass is defined as a tuple of (0,0) which doesn't pass this check. It is marked as illegal by the gtp library which then causes GnuGo to forfeit.

I added a check to allow a pass to return True in the vertex_in_range function locally and my network was able to respond correctly to passes and gomill functions as expected.

I will create a ticket for the gtp project and will post it here.

**Comment by robert-waite** [comment]
Issue from other repo:

https://github.com/jtauber/gtp/issues/4

**Comment by jtauber** [comment]
Thanks, let me take a look over there.

**Comment by jtauber** [comment]
Fixed and released as 0.3. Thanks for reporting it and suggesting the exact fix!
