### ISSUE TITLE
The project is out of updating?

### ISSUE THREAD

**Issue by nanxintin** [Rochester-NRT/RocAlphaGo#120]
I was very interested in the project and very grateful for you meaningful work. But I found that the project had been out of updating for several months. I was wondering if you were still working on this project and had any plan for future updating.
Thanks.

**Comment by aprescott** [comment]
The hiatus mentioned in https://github.com/Rochester-NRT/RocAlphaGo/issues/114 is relevant here. I believe the hiatus is expected to only be temporary.

**Comment by wrongu** [comment]
What @aprescott said is right. I'm personally unable to contribute until September, but other contributions are welcome
