### ISSUE TITLE
Rollout function only performs 1 rollout

### ISSUE THREAD

**Issue by robert-waite** [Rochester-NRT/RocAlphaGo#121]
_evaluate_rollout in mcts.py has a single loop which is passed the rollout_limit which is supposed to decide how many rollouts to try. The function instead uses it to determine how many moves in a single rollout before breaking (to prevent I suppose a game where the policy network has a never ending ko situation perhaps). There needs to be a second loop that retries the rollout loop for the number of times specified by rollout_limit. A new limit should be placed on the inner loop... I know one of the papers mentioned a limit they chose to detect an infinite situation.

Additionally... because it will now loop... the values output by the rollout (a 1 or a 0) need to be averaged. I imagine it should return that float directly and not return a 1 or 0.

I will play with it a bit and submit a pull request

**Comment by robert-waite** [comment]
Additionally... it might be useful for performance to check if a move is legal here. That way each call to the rollout_function passed in doesnt have to evaluate all legal moves before returning. That perhaps should be done on local branches as opposed to develop because it really is just a workaround to not having a fast rollout policy network available yet.

**Comment by wrongu** [comment]
The fast rollout policy is actually intended to return +/- 1 after a single evaluation. And you're right that the move limit is there to guard against infinite loops. There are a few other things to keep in mind here. First, any time you spend re-evaluating the leaf with the fast rollout policy is time you're not spending exploring other branches (plus there is the whole value network thing). Second, the ultimate goal is not to get a good evaluation of the leaves themselves (which are 20 moves into the future), but to get a good idea of what move to make _right now_, which comes from aggregating across thousands of leaves anyway!

You might get a slight speedup by optimizing when `is_legal` is called. I strongly recommend profiling the tree search first, though, because often there are much bigger fish to fry, e.g. optimizing copying game objects which is always surprisingly slow.

**Comment by robert-waite** [comment]
Yeah... I have a feeling I won't get much strength over just a single SL policy evaluation by using MCTS with my current hardware. It is probably just too slow at policy evaluations to expand the tree enough to get value.

It is true that the goal is not to get a good evaluation of the leaves... but... you do need to have some sort of valuation at the leaves to get any value from MCTS. For example... if every terminal leaf reported 50% chance of being good... then wouldnt the final evaluation of the tree just return what the base policy originally suggested at the root? It is only by learning that some leaves are better than others that the search tree can put a weight against the SL policy's suggestion.

And currently we don't have a value network or a fast policy network... so I don't have any function to evaluate the terminal leaf. My hope was that I could put some sort of function down there that would hopefully give a boost to playing strength. I am thinking though that if I can't run a fairly large number of branches in MCTS (perhaps due to my rate of policy network evaluations)... that my rollout results on terminal nodes will essentially randomly influence the tree to give less weight to the SL policy's suggestions (which are probably much more valid than the results of a weak rollout policy)

**Comment by wrongu** [comment]
Ah I see - you need something that can evaluate the leaves before having a value network ready. Maybe our MCTS class could be made more general.. but for now you could get away with subclassing it and overriding the `_evaluate_rollout` function. Pseudocode:

```python
class MCTSRandomRollout(MCTS):
  def __init__(self, n_random_rollout, *args, **kwargs):
    # call super constructor with args, kwargs
    self.n_random_rollout = n_random_rollout
  def _evaluate_rollout(self, state, limit):
    # perform self.n_random_rollout rollouts up to `limit` moves each time. return average of scores
```

**Comment by robert-waite** [comment]
Also... looking at some pre-AG papers... the group that was reported to get 44% accuracy with an SL had more numbers on accuracy with less layers. Perhaps I could train a 3 layer network with less filters that will get fair accuracy (better than total random rollout) and will run fast enough to use to rollout till end of game. I think the AG paper said the fast rollout policy network they used had an accuracy in the low 20s? Guessing still will be quite a bit slower than the fast policy from the paper... but maybe significantly faster than the full SL.

**Comment by robert-waite** [comment]
This ticket can be closed as the code is as intended.
