### ISSUE TITLE
Create a player class that uses MCTS

### ISSUE THREAD

**Issue by robert-waite** [Rochester-NRT/RocAlphaGo#122]
I have created an MCTSPolicyPlayer class to add to the ai.py file.

Need to polish a bit more but will submit PR

**Comment by robert-waite** [comment]
Created PR.. closing issue

**Comment by zongshuai818** [comment]
Hello ! @robert-waite 

i have a problem about MCTS on this [page](https://github.com/Rochester-NRT/RocAlphaGo/pull/147), if you remember something about using MCTS, place gave me some advice,  thank you !!
