### ISSUE TITLE
GameState.copy() doesn't create copy of history

### ISSUE THREAD

**Issue by robert-waite** [Rochester-NRT/RocAlphaGo#124]
Any copies created with share a single history list. Took a quick look at the code and seems that only mcts.py and renforcement_learning.py use copy

In the copy function we have:
other.history = self.history

Should be:
other.history = list(self.history)

**Comment by wrongu** [comment]
Good catch. Saw this before and thought we had fixed it already... I guess not. Can you make a quick PR?

(In case you didn't know, if you make a PR it creates an Issues thread just like this, so creating an Issue can be redundant if you're planning on doing a PR anyway)
