### ISSUE TITLE
More memory-efficient implementation of RL

### ISSUE THREAD

**Issue by wrongu** [Rochester-NRT/RocAlphaGo#131]
One minor and one major change can be made to the reinforcement_policy_trainer script.

1. Minor: remove state copies by computing feature planes before calling `do_move`
2. Major: rather than storing all feature planes for every position in the game, we could instead compute our own running gradient. Once the game ends we know whether the update should be + or - the gradient direction. While constant space (w.r.t. the length of the game) is nice, this would likely need to work around keras' `fit` API. Is added complexity worth the savings in space?

**Comment by robert-waite** [comment]
Just to give context.. I tried running batches of 64 games per minibatch... with 8G of ram... hit over 50% memory before main loop completed its second phase. There was a bit of memory churn which would let iterations complete.. but after a number of iterations... the application would reach for a little too much mem before released to OS and the linux OOM killer would activate.. signified by "Killed" being sent to stdout/stderr
