### ISSUE TITLE
SL restart overwrites weights

### ISSUE THREAD

**Issue by wrongu** [Rochester-NRT/RocAlphaGo#149]
"Restarting" with SL appends to the metadata, but overwrites weights starting again with weights.00000.hdf5. [#2557 in keras](http://github.com/fchollet/keras/pull/2557) was created as a way to fix this, but was not merged.

**Comment by wrongu** [comment]
Keras version 1.1.2 includes the `initial_epoch` argument to fit functions, making this fix now possible

**Comment by MaMiFreak** [comment]
fix included in cython version
