### ISSUE TITLE
tensorflow compatibility

### ISSUE THREAD

**Issue by wrongu** [Rochester-NRT/RocAlphaGo#158]
Allow either Theano or TensorFlow backends for Keras.
- [ ] verify that tensor shapes (e.g. in `preprocessing.py`) are compatible with both backends
- [ ] update travis CI to run tests using both backends
- [ ] make a TF-compatible version of RL

**Comment by MaMiFreak** [comment]
update 

RL indeed has to be rewritten.

most differences are handled by keras, important are the settings in keras.json
keras users with tensorflow have to set:
`"image_dim_ordering": "th"`
instead of tf, that way keras takes care of things. 
i'll write a test for it

**Comment by MaMiFreak** [comment]
travis CI is failing right now. don know much about it, will see what has to be changed when it is working again.

could you please add "verify resume learning between Theano and Tensorflow" 
I think there is a problem with that but somebody has to share a Theano trained model for that

tensor shapes are working with both backends

**Comment by MaMiFreak** [comment]
project is TF compatible
