### ISSUE TITLE
Reward is applied late.

### ISSUE THREAD

**Issue by oriskunk** [Rochester-NRT/RocAlphaGo#174]
I am testing RL.
After learning, I want to make sure that the probability of the action I did in this game was updated according to the results of the game.

First training RL.

    Batch 1	sampled opponent is weights.00000.hdf5
    Batch 2	sampled opponent is weights.00000.hdf5
    Batch 3	sampled opponent is weights.00000.hdf5
    ...

As a result, the following files have been created.

    -rw-rw-r--  1  31109952 11월 28 20:22 weights.00000.hdf5
    -rw-rw-r--  1  15558520 11월 28 20:23 weights.00001.hdf5
    -rw-rw-r--  1  15558520 11월 28 20:23 weights.00002.hdf5
    -rw-rw-r--  1  15558520 11월 28 20:24 weights.00003.hdf5

But the following two files are the same. The file size is different, but has the same output for the same state.

    weights.00000.hdf5 == weights.00001.hdf5

Is not it because of this code?

    is_learnable = current is learner and mv is not go.PASS_MOVE
        if is_learnable:
            (X, y) = _make_training_pair(state, mv, learner.policy.preprocessor)
        state.do_move(mv)
        if state.is_end_of_game:
            learner_is_winner = state.get_winner() == learner_color[idx]
            optimizer.set_result(idx, learner_is_winner)
            just_finished.append(idx)
        if is_learnable:
            optimizer.set_current_game(idx)
            learner_net.train_on_batch(X, y)

train_on_batch() is excuted before optimizer.set_result() is executed. : (
If I randomly set the result first, it seems to work normally.
weights.00000.hdf5  and weights.00001.hdf5 are different, and the result is also reflected.

Is there a reason to update before you set up game results?

**Comment by wrongu** [comment]
Looks to me like the problem isn't the order, but the fact that `is_learnable` will be false when the game is over (because of passing). I wonder why it isn't caught by the tests..

This version of RL needs replacing anyway. I had tried optimizing it to use less memory, but it became unusably slow.
