### ISSUE TITLE
Infinite loop, is_ladder_capture

### ISSUE THREAD

**Issue by MaMiFreak** [Rochester-NRT/RocAlphaGo#175]
found a sgf causing some sort of infinite loop in is_ladder_capture
[sgf can be found here](https://www.dropbox.com/sh/aoonq4ijw3onrda/AADn8IrVSnv4zKxTliuHN8Sma?dl=0)

remaining_attempts is decreasing with 2 ?
it looks like the same locations are checked over and over again

**Comment by oriskunk** [comment]
https://github.com/Rochester-NRT/RocAlphaGo/issues/174

**Comment by MaMiFreak** [comment]
ladder issue solved
