### ISSUE TITLE
Fix SL epoch number on restart

### ISSUE THREAD

**Issue by wrongu** [Rochester-NRT/RocAlphaGo#187]
Keras now includes an `initial_epoch` argument in its fit functions.

**Comment by MaMiFreak** [comment]
guess it has something to do with the new keras version:

`# AttributeError: 'NoneType' object has no attribute 'append'
    meta_writer.metadata["cmd_line_args"] \
       = meta_writer.metadata.get("cmd_line_args", []).append(vars(args))`

i am unsure on what the .get() should be doing with 2arguments
