### ISSUE TITLE
Definining "Ladder Capture" and "Ladder Escape"

### ISSUE THREAD

**Issue by wrongu** [Rochester-NRT/RocAlphaGo#20]
In Silver et al's paper, Extended Data Table 2 lists the features used as inputs to the policy and value networks. Exactly what moves are considered "ladder capture" and what are considered "ladder escape"?

Here is our best current interpretation:
- ladder capture: playing here reduces opponent’s liberties from 2 to 1 _and the resulting ladder can end in a capture of the opponent_ (checked via a potentially expensive search)
- ladder escape: playing here reduces opponent’s liberties from 2 to 1 _but the resulting ladder cannot end in a capture of the opponent_

It's not clear whether the above definition of ladder escape is a useful feature, however.

We also considered the definitions:
- ladder escape: playing here prevents the opponent from completing a ladder capture (though this is odd because from the opponent's perspective it never would have been defined as ladder capture in the first place)

**Comment by Nefeste** [comment]
Can the ladder breaker move considered as "ladder escape" feature? I guess you know what's the ladder breaker is.. http://senseis.xmp.net/?LadderBreaker

**Comment by thouis** [comment]
You could mail David Silver.  He was responsive when I asked about code for computing features being available (sadly, it's not).

My understanding of the Escape feature was "playing here increases liberties from 1 to 2 or 3, and if 2 does not result in a ladder capture."

Is ladder capture that expensive to search for?  If the group ever gets 3 liberties, it's no longer a ladder capture, though moves other than at the tip of the ladder have to be considered (in the case where playing out the ladder puts "chasing" stones in atari).

**Comment by Nefeste** [comment]
Also, move, that counters LadderBreaker can be considered as "ladder capture", not only the move, which reduces liberties from 2 to 1 imho ^^ Move that you can call "Ladder works again" =) You don't need to capture on any ladderbreaker-tenuki of opponent, but usually capture the ladder is an urgent move..

**Comment by LetterRip** [comment]
See Feugos files

GoLadder.cpp
FeBasicFeatures.cpp
GoUctLadderKnowledge.cpp

These define functions 
bool GoLadderUtil::IsLadderEscapeMove
bool GoLadderUtil::IsLadderCaptureMove

why reinvent the wheel...

**Comment by thouis** [comment]
On the note of not reinventing the wheel, I've started a Cython wrapper for Fuego:
https://github.com/thouis/pyfuego

I don't know if it would be useful or not, but it may be easier to re-use Fuego's code rather than reimplement it.

**Comment by LetterRip** [comment]
thouis, nice. See https://github.com/Rochester-NRT/AlphaGo/issues/48 that has a list of the functions we need that are already implemented in Fuego.

**Comment by wrongu** [comment]
Copying Fuego's definitions of ladder capture and ladder escape seems to be the way to proceed. Copying them will not be the difficult part, optimizing them will be.. and for the sake of starting supervised training, we do not need to compute features from a board blazingly fast.

@thouis we may come back to your pyfuego project later, but I think it would just obfuscate the process of computing features right now.

**Comment by thouis** [comment]
+1 on leaving it for now.  I'm going to add the rest of the AG features to the pyfuego code, and write an SGF-to-HDF5 writer, in the meantime.

Fuego has several small tests for capture/escape that I can try to extract in a form useful for this project.

**Comment by wrongu** [comment]
Good idea. I just made a separate ticket for upgrading the whole testing process to function more like Fuego's #59

**Comment by thouis** [comment]
I've finished writing the feature extractor in my fuego wrapper, and have started converting the KGS 6d+ archives to HDF5.  At some point, it would be good to compare features to make sure we agree (and understand where we don't).

**Comment by wrongu** [comment]
@thouis I'm curious what your thoughts are on formats for saving/loading tensor data. Is it a standard for go programs to concatenate data into large tensors and save as HDF5? Our current implementation is not very efficient - we're saving each training example in its own file, which at least has the advantage of making it easy to select random minibatches (simply loading random files)

@cjbates-mit can you push your current ladder code to a new branch so that we can compare with thouis'?

**Comment by thouis** [comment]
I don't know what's standard for Go programs.  For ML, I know many use HDF (we do so in our research).  The built-in compression is probably quite helpful for this sort of data.
