### ISSUE TITLE
What accuracy did you get for your SL policy network?

### ISSUE THREAD

**Issue by whstarxu54** [Rochester-NRT/RocAlphaGo#201]
AlphaGo claimed to have achieved an accuracy of 57% for the SL policy network. I wonder how much accuracy did you get for your SL training?

**Comment by MaMiFreak** [comment]
AG 57% SL net is a 256 filter network. SL used in their match version is a 192filter with 55.4% accuracy.
there is a difference in training with KGS data (as Daapmind did) and training with pro data,
with pro data validation accuracy is vastly lower when comparing two networks with the same strength

training results to my knowledge
47,8% (Pro data) ->less than one stone difference in playing strength
52.0% (KGS data) ->less than one stone difference in playing strength (achieved 53.2% today)
48.1% (Pro data)
