### ISSUE TITLE
Who can tell me how to start this game?

### ISSUE THREAD

**Issue by mervynn** [Rochester-NRT/RocAlphaGo#204]
I have configured the operating environment.

**Comment by MaMiFreak** [comment]
Have you checked [the wiki?](https://github.com/Rochester-NRT/RocAlphaGo/wiki)
I am not sure what your problem is exactly, a little more information would be useful

**Comment by FranzListzt** [comment]
I meant that I wanna play this game on an interface, such as some GUIs.
Otherwise, can u give me some advice about the entry of this project.
I am not goot at python, and I really wanna play it before researching the code. ^_^

**Comment by wrongu** [comment]
[This page](https://github.com/Rochester-NRT/RocAlphaGo/wiki/08.-Running-models-with-GTP) on the wiki explains how to play against a model using GoGui.

**Comment by mervynn** [comment]
Very thanks for your reply, and I am using GoGui, stdout: GTP engine ready.
But the process went down when I type "play" or some other keywords, do you know what happened.
this is the log:
Using TensorFlow backend.
GTP engine ready
play 
Traceback (most recent call last):
  File "greedy_player_gtp.py", line 13, in <module>
    run_gtp(player)
  File "/Users/hemingwei/Documents/Project/RocAlphaGo-develop/interface/gtp_wrapper.py", line 152, in run_gtp
    engine_reply = gtp_engine.send(cmd)
  File "/Library/Python/2.7/site-packages/gtp.py", line 151, in send
    message_id, getattr(self, "cmd_" + command)(arguments))
  File "/Library/Python/2.7/site-packages/gtp.py", line 208, in cmd_play
    move = parse_move(arguments)
  File "/Library/Python/2.7/site-packages/gtp.py", line 93, in parse_move
    color_string, vertex_string = (move_string.split(" ") + [None])[:2]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by mervynn** [comment]
The demo code seems need two files -"my_model_spec.json"/ "weights.00999.hdf5".
So lazy me used tests/test_date/minimodel.json and tests/test_date/hdf5/random_minimodel_weights.hdf5 as replacements of them.
Is there something wrong?

**Comment by MaMiFreak** [comment]
it seems you are using an older version, please make sure you are using the newest `develop` branch.
(your fork is is behind quite a bit)

i have to urge you to read the wiki, this project is till under development and it is better to understand a little of how it works when using it, also you would have [found](https://github.com/Rochester-NRT/RocAlphaGo/wiki/03.-Data) where you can find pre-trained weight and corresponding model files;-)
