### ISSUE TITLE
Faster feature computation

### ISSUE THREAD

**Issue by wrongu** [Rochester-NRT/RocAlphaGo#206]
Feature computations in `preprocessing.py` need to be faster. Things to consider:

- avoid `numpy.concatenate` by preallocating and passing target indices to each feature function
- compute all 'lookahead' features together, i.e. those that involve seeing what happens when a stone is played. `capture_size`, `self_atari_size`, and `liberties_after` all do this.
- cache precomputed features (#170, but does not currently play nicely with the first bullet here)
- rewrite preprocessing.py in cython (see also #205)

**Comment by MaMiFreak** [comment]
except cache precomputed features everythin is implemented in cython update
