### ISSUE TITLE
How to solve the unknown layer: Bias mistake?

### ISSUE THREAD

**Issue by Coolioluo** [Rochester-NRT/RocAlphaGo#208]
execute:
python -m AlphaGo.training.supervised_policy_trainer my_model.json debug_feature_planes.hdf5 training_results/ --epochs 5 --minibatch 32 --learning-rate 0.01

result:
  File "D:\tensorflow\RocAlphaGo\RocAlphaGo-develop\AlphaGo\models\nn_util.py", line 79, in load_model
    new_net.model = model_from_json(object_specs['keras_model'], custom_objects={'Bias': Bias})
...
ValueError: Unknown layer: Bias

Thx

**Comment by wrongu** [comment]
Never seen this before. Please make sure your keras version matches what's in `requirements.txt`. If that doesn't help, can you paste the contents of `my_model.json` here?

**Comment by Coolioluo** [comment]
Name: Keras
Version: 2.0.1
Summary: Deep Learning for Python
Home-page: https://github.com/fchollet/keras

{"keras_model": "{\"keras_version\": \"2.0.1\", \"config\": [{\"config\": {\"name\": \"conv2d_1\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 128, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [5, 5], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"relu\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"dtype\": \"float32\", \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"batch_input_shape\": [null, 12, 19, 19], \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"conv2d_2\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 128, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [3, 3], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"relu\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"conv2d_3\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 128, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [3, 3], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"relu\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"conv2d_4\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 128, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [3, 3], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"relu\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"conv2d_5\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 128, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [3, 3], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"relu\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"conv2d_6\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 128, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [3, 3], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"relu\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"conv2d_7\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 128, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [3, 3], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"relu\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"conv2d_8\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 128, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [3, 3], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"relu\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"conv2d_9\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 128, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [3, 3], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"relu\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"conv2d_10\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 128, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [3, 3], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"relu\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"conv2d_11\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 128, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [3, 3], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"relu\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"conv2d_12\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 128, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [3, 3], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"relu\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"conv2d_13\", \"data_format\": \"channels_first\", \"dilation_rate\": [1, 1], \"filters\": 1, \"use_bias\": true, \"activity_regularizer\": null, \"kernel_size\": [1, 1], \"bias_regularizer\": null, \"kernel_initializer\": {\"config\": {\"seed\": null, \"maxval\": 0.05, \"minval\": -0.05}, \"class_name\": \"RandomUniform\"}, \"kernel_regularizer\": null, \"bias_constraint\": null, \"activation\": \"linear\", \"bias_initializer\": {\"config\": {}, \"class_name\": \"Zeros\"}, \"strides\": [1, 1], \"kernel_constraint\": null, \"trainable\": true, \"padding\": \"same\"}, \"class_name\": \"Conv2D\"}, {\"config\": {\"name\": \"flatten_1\", \"trainable\": true}, \"class_name\": \"Flatten\"}, {\"config\": {\"name\": \"bias_1\", \"trainable\": true}, \"class_name\": \"Bias\"}, {\"config\": {\"name\": \"activation_1\", \"activation\": \"softmax\", \"trainable\": true}, \"class_name\": \"Activation\"}], \"class_name\": \"Sequential\", \"backend\": \"tensorflow\"}", "feature_list": ["board", "ones", "turns_since"], "class": "CNNPolicy"}

Above is the information, Thx

**Comment by Coolioluo** [comment]
Traceback (most recent call last):
  File "C:\Users\coolioluo\Anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\coolioluo\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\tensorflow\RocAlphaGo\RocAlphaGo-develop\AlphaGo\training\supervised_policy_trainer.py", line 267, in <module>
    run_training()
  File "D:\tensorflow\RocAlphaGo\RocAlphaGo-develop\AlphaGo\training\supervised_policy_trainer.py", line 131, in run_training
    policy = CNNPolicy.load_model(args.model)
  File "D:\tensorflow\RocAlphaGo\RocAlphaGo-develop\AlphaGo\models\nn_util.py", line 79, in load_model
    new_net.model = model_from_json(object_specs['keras_model'], custom_objects={'Bias': Bias})
  File "C:\Users\coolioluo\Anaconda3\lib\site-packages\keras\models.py", line 325, in model_from_json
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Users\coolioluo\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "C:\Users\coolioluo\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 141, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "C:\Users\coolioluo\Anaconda3\lib\site-packages\keras\models.py", line 1186, in from_config
    layer = layer_module.deserialize(conf)
  File "C:\Users\coolioluo\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "C:\Users\coolioluo\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 133, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: Bias

**Comment by wrongu** [comment]
This looks like an incompatibility with keras 2. We may someday need to implement a custom `from_config` function in our `Bias` layer..

In the meantime, I recommend creating a virtual environment for this project and using the exact package versions that we've tested (i.e. `pip install -r requirements.txt` from within your virtualenv)

**Comment by Coolioluo** [comment]
Thanks a lots, I have solved the keras problem by your way. But I meet a new problem, because i use windows tensorflow, the python version must be 3.5. That means there are some incompatible between python2.7 and 3.5, it is a hard work to modify the code to 3.5. Anyway, still thanks, this issue can be closed.

**Comment by Coolioluo** [comment]
Good news，I have solve the incompatible between 2.7 and 3.5. It is starting training, in the envirement win10/tensorflow1.0/python3.5. Thank you again
