### ISSUE TITLE
test-case about ladder search is probably wrong

### ISSUE THREAD

**Issue by PatWie** [Rochester-NRT/RocAlphaGo#213]
I am not a very good GO-player, but the test-case:
https://github.com/Rochester-NRT/RocAlphaGo/blob/develop/tests/test_ladders.py#L71-L81
seems wrong to me. Black can always capture the white group when playing 'a' --even when white answers by playing `b` in
```
parseboardrd.parse(". O X b . .|"
```

Here are all possible tree expansions:
https://gist.github.com/PatWie/878119f28306c6e6625303d45242f5d7

**Comment by MaMiFreak** [comment]
Thank you for checking the test-cases! 
there is a second sequence white can try to escape the ladder and that one is able to escape, i included a .txt(you have to rename it to .sgf) with some variations: [ladder.txt](https://github.com/Rochester-NRT/RocAlphaGo/files/1118123/ladder.txt)

**Comment by PatWie** [comment]
Ah ok.
