### ISSUE TITLE
How to use the GoGui

### ISSUE THREAD

**Issue by WeakDog** [Rochester-NRT/RocAlphaGo#217]
I have run the examples of supervised policy network following the Wiki and got the 'model.json' and 'weights.#####.hdf5' data.  And it also seems OK by running the examples 'greedy_player_gtp.py'. Then I want to make it interface with the GoGui, but I don't really know how to do it. In the Wiki, it says that "attach this program using whatever command you use to run it". I don't really know what this means. Does it mean attaching the 'greedy_player_gtp.py' to GoGui?

**Comment by MaMiFreak** [comment]
Well that is something you have to check with the GoGui and and the software you are running like virtualenv/docker/anaconda.
You need to start a new instance of python and give the location of  'greedy_player_gtp.py' and the correct way to do this depends on the environment you are running.

I used it a while ago in combination with `virtualenv` using the information in our wiki:
"/path/to/your/virtualenv/bin/python greedy_player_gtp.py" (the exact location can be different on your machine)

**Comment by WeakDog** [comment]
Thanks for your comments!
According to your suggestions, I run it and then it shows this 

![image](https://user-images.githubusercontent.com/30678982/29165961-3454ba68-7df7-11e7-8108-fc8ffbae3dd7.png)

I think it's OK with the GTP, but still doesn't start the GoGui
I still don't know how to use the GoGui
I have also used the command 'save_sgf' but it doesn't work in the GTP.
Is there anything wrong?

**Comment by weehowe-z** [comment]
Have you ever tried to start GoGUI from a command line?
Please use search engines first.

```shell
gogui-twogtp -black <Instruction> -white <Instruction>  .... other params ...
```

where `<Instruction>` can be   `python greedy_player_gtp.py`, `gogui-display` ....

[gogui-twogtp man page](https://www.mankier.com/1/gogui-twogtp)

**Comment by godmoves** [comment]
Hi, WeakDog! 
Can you tell me how to write the  'greedy_player_gtp.py'? 
I've tried several times, but it always reports `IOError: Unable to open file (File signature not found)`

**Comment by MaMiFreak** [comment]
@godmoves could you provide the code you used? i suspect a file reference is the issue here.

**Comment by godmoves** [comment]
Here is my code:
```
from AlphaGo.ai import GreedyPolicyPlayer
from AlphaGo.models.policy import CNNPolicy
from interface.gtp_wrapper import run_gtp

MODEL = '../Rocalphago-data/training_results/supervised/48plane_Community_bias/metadata.json'
WEIGHTS = '../Rocalphago-data/training_results/supervised/48plane_Community_bias/weights.01700.hdf5'

policy = CNNPolicy.load_model(MODEL)
policy.model.load_weights(WEIGHTS)

player = GreedyPolicyPlayer(policy)

run_gtp(player)
```
And now it returns:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "zgreddy_player.py", line 8, in <module>
    policy = CNNPolicy.load_model(MODEL)
  File "/home/pwjtc/Work/RocAlphaGo-cython/AlphaGo/models/nn_util.py", line 81, in load_model
    new_net = network_class(object_specs['feature_list'], init_network=False)
KeyError: 'feature_list'
```

**Comment by MaMiFreak** [comment]
the code you use is correct, only the `.metadate.json` file is not the model. it is used to store training results like accuracy etc. in guess the model file you want to use is located at `../Rocalphago-data/models/CNNPolicy/48plane_bias.json`

**Comment by godmoves** [comment]
@MaMiFreak It seems all the weights I downloaded from `Rocalphago.data` are broken. They all become about 132 byte and can not be loaded. I don't whether I made some mistakes or the data wrong itself. Can you check it?

**Comment by MaMiFreak** [comment]
i can download the files just fine, have you tried to download the whole repo as a zip?

**Comment by godmoves** [comment]
I tried to git clone and download as zip, but both of them don't work. Maybe I should try again later.
