### ISSUE TITLE
How to train the value network and the reinforcement value network?  

### ISSUE THREAD

**Issue by YHangbin** [Rochester-NRT/RocAlphaGo#218]
I have run the examples of supervised policy network following the Wiki . but I don't know how to train the value network and the reinforcement value network ,in the branch :https://github.com/MaMiFreak/RocAlphaGo/tree/debug-valueI only see the reinforcement_value_trainer.py and I don't really know how to use it.thank you for your help.

**Comment by MaMiFreak** [comment]
i answered your question in #219 

most important thing is to check out the [cython-optimization](https://github.com/Rochester-NRT/RocAlphaGo/tree/cython-optimization) branch. let me know if you run into any trouble

**Comment by YHangbin** [comment]
@MaMiFreak  OK ,I will try it. Thank you for answering my question!
