### ISSUE TITLE
Ask for permission.

### ISSUE THREAD

**Issue by Sun1Plus** [Rochester-NRT/RocAlphaGo#228]
Hello, thanks for your work! In your project, I have learned a lot of knowledge. I would like to take part of your codes as part of my Undergraduate graduation design. How do I write this part for you in my papers and codes? 

Best wishes to you!

**Comment by wrongu** [comment]
Glad you found it useful! We have an MIT license. This means you are of course free to reuse or publish our code  essentially as long as you cite the project (include our license statement)
