### ISSUE TITLE
Some problems in go engine

### ISSUE THREAD

**Issue by CezCz** [Rochester-NRT/RocAlphaGo#229]
You have really nice implementation of go rules, however while doing MCTS it provides nodes with illegal moves. I have tracked down several bugs, and mitigated the problem which still persists. Do you know what may be the cause ?

To replicate the issue you can try to check illegal move 
```
moves = ["some game, unfortunately I haven't recorded any"]

game = go.GameState(9)
illegal_move = ["illegal move in given state after moves"]

for move in moves:
   game.do_move(move)
   game = game.copy()
game.is_legal(illegal_move) # This will be True now, which is wrong
```

Now I have tracked several problems which mitigated the problem, but not fixed it completely:

function _update_neighbors does not update liberty_sets for opponents groups:
```
if self.board[nx][ny] == -self.current_player:
   new_liberty_count = len(self.liberty_sets[nx][ny])
      for (gx, gy) in self.group_sets[nx][ny]:
         self.liberty_sets[gx][gy] -= set([position]) # MISSING
         self.liberty_counts[gx][gy] = new_liberty_count
```

copy operation has some problems, following copy operation had some fault I couldn't track. 
```
        for x in range(self.size):
            for y in range(self.size):
                other.group_sets[x][y] = set(self.group_sets[x][y])
                other.liberty_sets[x][y] = set(self.liberty_sets[x][y])
```

I have changed it to:

```
other.group_sets = deepcopy(self.group_sets)
other.liberty_sets = deepcopy(self.liberty_sets)
```

It all helped the issue, but it still happens every let's say 10000 mcts rollouts, do you by any chance have any clues what may cause it ?

**Comment by CezCz** [comment]
I just notices these problems were addressed in this fork https://github.com/vftens/RocAlphaGo

**Comment by wrongu** [comment]
Can you try using the `cython-optimization' branch and see if the bug persists? The latest development in this repository has been there.

**Comment by CezCz** [comment]
Hey thanks for response, sure I'll try it

**Comment by CezCz** [comment]
Hey, the problem still persists. It happens once every ~600 generated 9x9 games. I have alpha go zero inspired solution on repo (https://github.com/CezCz/CezGo). It still has a lot of polishing left to be done, but simply run main.py and it will start training pipeline. 

P.S I have added caching as network was a huge bottleneck for me, will try without it but it's going to take a while.

**Comment by wrongu** [comment]
Can you share the exact code that is causing the issue? Unless I can reproduce the error I'm not sure where to look.

If you're using our MCTS code, I have fewer guarantees – we never got MCTS fully working and tested.

By the way, you're free to use any of our code as part of your project, but you need to keep a copy of our license with it.

**Comment by wrongu** [comment]
Glad to hear it. Before the cython changes, I had my own feature caching branch, since computing the features can be more of a bottleneck than running the network. You might try that – code is [here](https://github.com/wrongu/RocAlphaGo/tree/preprocessing_cache/AlphaGo/preprocessing)
