### ISSUE TITLE
How do I contribute

### ISSUE THREAD

**Issue by AntreasAntoniou** [Rochester-NRT/RocAlphaGo#35]
Title sais it all. I have 3 hours per weekday, 4 hours per weekend day for this. Please let me know. :)

**Comment by wrongu** [comment]
We appreciate it! We are a small team and have been organizing privately up until now. Given the recent interest, we will do our best to put our design specs on the project wiki and our to-do list on the issues page as soon as possible - stay tuned!

**Comment by AntreasAntoniou** [comment]
I was actually intending to do this myself. If I was a student I would have probably had started something similar, but my job has been taking most of my time and yeah.. ;p

**Comment by AntreasAntoniou** [comment]
So I might as well help you guys out!

**Comment by Nefeste** [comment]
Did you guys affiliated with Facebook somehow? )

**Comment by lancerts** [comment]
Also interested in contribute here!

**Comment by grass0916** [comment]
:+1:

**Comment by firearasi** [comment]
Is it ok If I try to "port" this to other "platforms" like mxnet?
I am a newbie in deep learning~

**Comment by cheng6076** [comment]
want to contribute too

**Comment by wrongu** [comment]
@Nefeste we are a group of data science students, not affiliated with facebook

@firearasi of course! Really the deep learning part of AlphaGo isn't the technically challenging part, though. In fact, once we have started the training process, we will be able to provide pre-trained model parameters in a universal format so that running the neural nets in any system (torch/caffe/mxnet/etc) is relatively easy. The difficult part for any implementation will be optimizing the tree search and neural nets together

**Comment by dimykus** [comment]
Can you explain how goServer works? I'm trying fix #34, but I don't understand how it should works. What should happen after sgf uploading? Server tries redirect me to the uploaded file and returns 404, because it uses wrong path.

**Comment by AntreasAntoniou** [comment]
@wrongu How can I contact you? I want to share some of my details with you(so you can check my suitability to work with you guys).

**Comment by Nefeste** [comment]
@wrongu Ok than ) btw i have a lot of sgf-files with top professionals games from recent tournaments.. It can be useful to prepare the first stage of NN training

**Comment by wrongu** [comment]
@Nefeste absolutely - the more expert SGF data we have the better. We only have a single dataset so far. We will need to look into whether we have permission to open-source that as well.

**Comment by wrongu** [comment]
@AntreasAntoniou there is not much to check! Pull requests are a meritocratic system

**Comment by AntreasAntoniou** [comment]
@wrongu Awesome then! Looking forward to this.

**Comment by happygds** [comment]
Hi, what do you guys plan to develop next?

**Comment by LetterRip** [comment]
Would appreciate if you could put your todo list, etc. on the wiki as soon as reasonably feasibly.  I think there are a lot of people interested in contributing but don't want to write code that you have in progress.

**Comment by wrongu** [comment]
We will have the wiki and todo list up tomorrow, which is the earliest time our team is able to meet!

**Comment by gogogeo** [comment]
Hello,
there is free and big (58444 games) pro game database under this link
https://badukmovies.com/pro_games/download
I like python :+1:

**Comment by wrongu** [comment]
@gogogeo thanks! Downloaded it.

**Comment by skyer9** [comment]
alphago learned with kgs sgf data
http://www.u-go.net/gamerecords/

but i prefer 58444 games data from
https://badukmovies.com/pro_games/download

it is PRO game data.

**Comment by AntreasAntoniou** [comment]
@skyer9 It also needs to be trained or non-pro data, so that it can see moves that are not-that-good in addition to really good ones, in order for it to model the game in more depth. E.g. AlphaGo didn't know about the type of move Lee Sedol played in game 4 when he turned the game around because it mostly played itself, that played at the level of super-pro. Therefore missing observations on different kinds of moves.

**Comment by ScrumUser1** [comment]
Hello My name is Ricardo, I am a graduate in computer science and interested in contributing to an open source project.I would like to know more about this please and stay in contact? My hours are varied but available to help and would like to learn aswell.
