### ISSUE TITLE
Opinion on PEP8 violations

### ISSUE THREAD

**Issue by jtauber** [Rochester-NRT/RocAlphaGo#44]
I just ran `flake8` on the **develop** branch and got 2262 violations.

I'm happy to clean this up and hook up flake8 as part of travis-ci but wanted to get the developers' opinion on PEP8 violations first.

**Comment by jtauber** [comment]
Most (but not all) of the violations are due to use of tabs rather than spaces for indentation.

**Comment by wrongu** [comment]
Personal opinion: I've always been partial to tabs over spaces. How egregious are the violations once those are ignored?

**Comment by jtauber** [comment]
I'll see if I can run flake8 allowing for tabs (which are not PEP8 style, but might be configurable)

**Comment by jtauber** [comment]
Here's a summary of what's currently being violated:

```
28      E101 indentation contains mixed spaces and tabs
1       E125 continuation line with same indent as next logical line
14      E128 continuation line under-indented for visual indent
13      E203 whitespace before ':'
2       E221 multiple spaces before operator
11      E223 tab before operator
365     E231 missing whitespace after ','
4       E251 unexpected spaces around keyword / parameter equals
50      E261 at least two spaces before inline comment
6       E262 inline comment should start with '# '
2       E265 block comment should start with '# '
4       E266 too many leading '#' for block comment
34      E302 expected 2 blank lines, found 1
2       E303 too many blank lines (2)
2       E401 multiple imports on one line
8       E402 module level import not at top of file
63      E501 line too long (81 > 79 characters)
4       E701 multiple statements on one line (colon)
1       E713 test for membership should be 'not in'
2       F401 'np' imported but unused
1596    W191 indentation contains tabs
28      W291 trailing whitespace
7       W292 no newline at end of file
11      W293 blank line contains whitespace
4       W601 .has_key() is deprecated, use 'in'
```

Note that quite a few of the issues are in sgflib. I actually have an alternative python sgf library if you want one that's MIT licensed and (will be) actively developed.

**Comment by wrongu** [comment]
Since it looks pretty easy to [configure flake8](http://flake8.readthedocs.org/en/latest/config.html) to ignore W191 and the sgflib directory, I think it would be a good addition to the project to have this done by Travis. It looks like a not-unreasonable number of things would need to be changed to fix the current violations. The sooner it is added the more painless the process will be!

**Comment by jtauber** [comment]
I'll initially set up flake8 to ignore W191 and the sgflib and fix the violations.

One warning about ignoring W191: it won't prevent people from using spaces for indentation, just allow them to use tabs. So it could lead to inconsistency.

**Comment by jtauber** [comment]
I almost have a PR ready. Just testing on Travis first.

I'm running with following configuration

```
[flake8]
ignore = W191,E266,E501
exclude = AlphaGo/models/sgflib
```

Further to my warning about ignoring W191: there are actually files that use spaces not tabs but I can't detect those with flake8 as PEP8 considers spaces correct.

There were a couple of files that mixed spaces and tabs but I converted them to all tabs for now.

**Comment by jtauber** [comment]
Update version ready to go at #68
