### ISSUE TITLE
Detecting end of game

### ISSUE THREAD

**Issue by cjbates-mit** [Rochester-NRT/RocAlphaGo#47]
While running my self-play benchmark (greedy_player_benchmark.py), I realized that we are currently not detecting whether a move represents end of game. I'm proposing that we can detect this event as two pass moves in a row. In my branch (player), I have defined a pass as action=None, and created a new function, do_pass_move in GameState, which appends the None move to self.history, switches player, and adds 1 to number of turns played. In AlphaGo.ai.GreedyPolicyPlayer.get_move I check to see if there are any legal moves available, and if there are none, I return None, which will be interpreted as a pass move in Play.play_match. In Play.play_match, I also keep track of whether each player has passed, and if there are two passes in a row, I return end_of_game=True from the play function. Would any of this present a problem in any way (e.g. having None's in the game state history)?

However, just passing when there are no legal moves available doesn't seem to be sufficient for end of game, because the game may still go on ad nauseam. We need another criterion (according to https://www.gokgs.com/tutorial/gameEnd.jsp) that looks at whether a move increases your score. If it doesn't, we should pass. I suppose in order to do this, we need to pretend that the move we are currently considering is the end of the game, and call a function to sum up the score. Do I have this right? If so, I can work on implementation.

**Comment by wrongu** [comment]
Passes (i.e. action is `None`) should be handled just fine by `GameState` (there is a [PASS_MOVE](https://github.com/Rochester-NRT/AlphaGo/blob/develop/AlphaGo/go.py#L6) constant set to `None`).

If there are two passes in a row, `GameState` itself should probably flag that the game is over. (Two or three passes, really - it must end on white passing). There is also the subtle rule that the captured stone count should be incremented on a pass.

I interpret the given gokgs link as guidelines for human players.. My impression was that greedy playouts would just continue until there were no legal moves left and that this wouldn't have any problems

**Comment by cjbates-mit** [comment]
Whoops, I missed the PASS_MOVE constant. I've removed the `do_pass_move` function I made. I added in code for incrementing capture stone count on a pass, and also added a return statement for the end of game condition in `do_move`.

> My impression was that greedy playouts would just continue until there were no legal moves left and that this wouldn't have any problems 

This isn't true. I specifically ran into the problem of games continuing forever. Printing out the board states, it seems that when a bunch of pieces finally get captured, then there are a bunch of open spaces to play in again, and the game continues from there. Game play was running for thousands of moves before I halted it.

**Comment by cjbates-mit** [comment]
Also, I think something funny happens when the entire board is filled with one player. I think it switches all the spaces to empty. Something like that.

**Comment by wrongu** [comment]
Clarification: play out to the end _but not filling eyes_ should work. Looks like most other computer go programs ignore _seki_ and just call the final score approximate..

I found looking at Fuego's scoring functions (`GoBoardUtil.h` and `GoBoardUtil.cpp`) and how they're called useful

**Comment by cjbates-mit** [comment]
I think this issue may be resolved in general by making sure a policy player only returns sensible moves (i.e. don't play in own eye). See `ai.GreedyPolicyPlayer` for example of how this works. Games still take a while to roll out in this way, however. May want to consider more sophisticated end-of-game detection in the future.
