### ISSUE TITLE
GPU training and scaling

### ISSUE THREAD

**Issue by LetterRip** [Rochester-NRT/RocAlphaGo#49]
Obviously 50-60 GPUs simultaneously training for 4 weeks is less than ideal, in that we probably lack access to a cluster with that many GPUs and don't want to wait a month for the training to occur.

My thoughts were that we could preprocess the position samples, upload them and use something like 

http://cs.stanford.edu/people/karpathy/convnetjs/

For the training - with people simply going to the site, pressing start, and a batch of games with the current weights for current net is provided to them and it automatically returns the results after the batch finishes.  Perhaps the owner of that site would be willing and interested to help set up the customization.

Then we announce on one the go servers/forums the dates that we plan to use, and people simply pop on to the site when they have some spare time on their computer.  It seems possible that this would allow us to converge far faster.

If there are enough people we could train multiple nets at the same time (There might literally be millions of people interested in donating compute cycles).

**Comment by wrongu** [comment]
We actually have a sizeable computing cluster here at the University of Rochester. We were planning to train the models ourselves and release the trained weights across multiple epochs. We don't have 50-60 GPUs, though, so training time may actually turn out to be an issue.. in which case we'll have to start considering other options like renting time from Amazon/Google.

Correct me if I'm wrong, but it looks liks convnetjs is good for _smaller_ datasets to be trained in-browser, not for networked/distributed training (which is a non-trivial problem in general)

**Comment by LetterRip** [comment]
It is designed for smaller datasets to be trained in-browser.  I'm aware of the non trivial nature of networked/distributed training - but the problems are mostly efficiency related I suspect.  If you are willing to 'waste' resources (ie 500 people training being the equivalent of a 40 GPU trained system) then I don't think it is as difficult a problem (trying to see what the literature says on this...).

**Comment by wrongu** [comment]
I found this page very informative: [[https://www.quora.com/What-are-some-distributed-SGD-implementations]]

**Comment by wrongu** [comment]
https://github.com/maxpumperla/elephas
www.ics.uci.edu/~welling/publications/papers/MLinBrowser.pdf

**Comment by LetterRip** [comment]
Yes those look very much along the lines of what I was thinking.

**Comment by LetterRip** [comment]
It might be interesting to train the networks on different sized games.  Testing and evaluation on smaller games (9x9) should give a lot more certainty as to play quality.

**Comment by wrongu** [comment]
Definitely - we were thinking about testing the pipeline on smaller boards, where other AIs can serve as 'experts' and be used to generate any amount of training data. Nothing in the current state/feature processing/training code really requires 19x19 boards, [though it was sort of assumed here](https://github.com/Rochester-NRT/AlphaGo/blob/training/AlphaGo/preprocessing/game_converter.py#L37). I believe that's the only line that would need to be changed to run the training on smaller games.

**Comment by ttrine** [comment]
Leaving this remark here because it's too similar to open up a distinct issue. I've written the supervised policy training routine in such a way that it will (hopefully) transfer seamlessly to one or more GPUs. I'm planing to get this working on our university computing cluster tonight or tomorrow.

**Comment by ttrine** [comment]
OK I verified that training works on GPU as expected. model.fit_generator() asks how many workers it should use. Is there a way to programmatically estimate a good number of workers? Or do we have to do it manually?
